name: "release version"
on:
  push:
    branches:
      - "development"
jobs:
  tagged-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: '16'
      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GIT_TOKEN }}
          prerelease: false
          files: ./*
          