name: "release version"
on:
  push:
    branches:
      - "development"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create or update release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GIT_TOKEN }}
          prerelease: false
          files: |
            ./*
          body: |
            ${{ steps.changelog.outputs.changelog }}