name: "release version"
on:
  push:
    branches:
      - "development"
jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: ubuntu-latest
    steps:
      - name: Create release
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GIT_TOKEN }}
          prerelease: false
          files: |
            ./*
          